version: 2.1

parameters:
  trigger:
    type: boolean
    default: false

workflows:
  main-workflow:
    when:
      not: << pipeline.parameters.trigger >>
    jobs:
      - renovate-config-validator:
          context: image-publishing
  triggered-workflow:
    when: << pipeline.parameters.trigger >>
    jobs:
      - renovate-config-validator:
          context: image-publishing

jobs:
  renovate-config-validator:
    environment:
      LOG_LEVEL: DEBUG
      RENOVATE_CONFIG_FILE: renovate.json5
    docker:
      - image: renovate/renovate
    steps:
      - checkout
      - run: renovate-config-validator
      - run: |
          RENOVATE_AUTODISCOVER_FILTER="JalexChen/renovate/"
          renovate --token=$GITHUB_TOKEN --autodiscover
